IN-11908: Add table mutation
tekliner/chproxy pull request #1
Opened 2024-02-15 07:22 UTC by AKuzyashin

https://improvado.atlassian.net/browse/IN-11908

2024-02-15 07:39 UTC, VladimirZaytsev commented on proxy_test.go
> +			bodyOrQuery:  "CREATE TABLE db.table ENGINE = MergeTree() ORDER BY id",
Но ведь тут мы должны получить тоже измененный запрос вида:
```
CREATE TABLE db.table ENGINE = ReplicadetMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/db/table', '{replica}') ORDER BY id
```

2024-02-15 09:23 UTC, granescb approved these changes

2024-02-15 09:52 UTC, VladimirZaytsev commented on proxy_test.go
> +	}
Добавь тест на то, как себя поведет код, если мы захотим выполнить запрос вида:
```
create table db.table_name  ENGINE = ReplicatedMergeTree('/path', '{replica}', Sign) order by id
```

2024-02-15 11:38 UTC, VladimirZaytsev commented on scope.go
> +	re := regexp.MustCompile(`(?i)engine\s*=\s*(CollapsingMergeTree|MergeTree|ReplacingMergeTree|SummingMergeTree|AggregatingMergeTree|VersionedCollapsingMergeTree|GraphiteMergeTree)\(([^)]+)\)`)
Вынесли плз эту регулярку в константы сверху

2024-02-15 11:41 UTC, VladimirZaytsev commented on scope.go
> +	re := regexp.MustCompile(`(?i)engine\s*=\s*(CollapsingMergeTree|MergeTree|ReplacingMergeTree|SummingMergeTree|AggregatingMergeTree|VersionedCollapsingMergeTree|GraphiteMergeTree)\(([^)]+)\)`)
Выглядит не очень. Кх могут добавлять новые движки, а нам нужно будет поддерживать этот код. Сделай регулярку которая будет понимать, что в движке есть "MergeTree" и нет слова "Replicated". Тогда подставлять перед ним префикс "Replicated" и скобочки с инфой

2024-02-15 11:44 UTC, VladimirZaytsev commented on scope.go
> +	m := re.FindStringSubmatch(query)
А любимый гошный "m,err := ..; if (err) {panic}"? Не надо тут? Ну и в других местах. Просто вспомнилось, проверь пж что везде где надо стоит

2024-02-15 11:48 UTC, VladimirZaytsev commented on scope.go
> +	re = regexp.MustCompile(`(?i)create\s+table\s+(\S+)`)
Не может ли в кх быть edge кейсов, когда ты пишешь что-то типо:
```
create cool table engine=MergeTree;
```
?

Есть что-то типо temporary или in_memory таблиц. Тут бы собрать пачку запросов из system.query_log где есть слово create и проанализировать. Нужно сделать качественный прокси, чтобы не объебаться в будущем в каком-то неожиданном месте

2024-02-15 11:51 UTC, VladimirZaytsev commented on scope.go
> +	fullZooKepPrefix := zooKepPrefix + dbName + "/" + tableName
```suggestion
	fullZooKepPath := zooKepPrefix + dbName + "/" + tableName
```

2024-02-15 11:54 UTC, AKuzyashin commented on scope.go
> +	m := re.FindStringSubmatch(query)
тут не надо

2024-02-15 12:04 UTC, VladimirZaytsev commented on scope.go
> +	engine := fmt.Sprintf("ENGINE = Replicated%s('%s', '{replica}', %s)", m[1], fullZooKepPrefix, m[2])
Слушай, тут в доке есть примеры, когда не используется параметр после слова '{replica}'. Что это за параметр? Когда его нужно, а когда не нужно проставлять? 

![Screenshot from 2024-02-15 18-57-23](https://github.com/tekliner/chproxy/assets/34230580/b3b6a809-b925-47a9-aefd-77f0aafe4fa9)

2024-02-15 12:04 UTC, VladimirZaytsev commented on scope.go
> +	// replace MergeTree engine with ReplicatedCollapsingMergeTree
```suggestion
	// replace MergeTree engine with ReplicatedMergeTree
```

2024-02-16 02:10 UTC, AKuzyashin commented on scope.go
> +	engine := fmt.Sprintf("ENGINE = Replicated%s('%s', '{replica}', %s)", m[1], fullZooKepPrefix, m[2])
я так понимаю, что это не обязательный апарметр. Котороый можно omit

2024-02-16 05:47 UTC, vegassor commented on go.mod
> +go 1.20
Почему 1.20? Уже 1.22 вышла

2024-02-16 08:13 UTC, AKuzyashin commented on go.mod
> +go 1.20
Совсем недавно же вышло. Может подождать?

2024-02-21 08:08 UTC, fantom0005 requested changes

2024-02-21 08:08 UTC, fantom0005 commented on proxy_test.go
> +			wantQueryPart := fmt.Sprintf("Replicated%s('/clickhouse/{installation}/{cluster}/tables/{shard}/db/table/b57246e0-4530-4104-b91e-9229b7aec227', '{replica}', Sign)", engine)
не у всех же MergeTree есть sign.

лучше в тест выше добавить реальные примерами с разным типом движков. Особенно с обычным MergeTree

2024-02-21 08:08 UTC, fantom0005 commented on proxy_test.go
> +	t.Run("POST without MergeTree", func(t *testing.T) {
вот это тоже в параметризацию можно вынести теста выше

2024-02-21 08:08 UTC, fantom0005 commented on proxy_test.go
> +		match := regex.FindStringSubmatch(tc.Query)
вообще непонятно что приизсходит тут.
тебе нужно сделать функцию getTableNameFromCreateTableQuery. и тут ее тестировать.

т.е. тебе не сам regexp нужно тестить, а функцию. т.е. ты можешь потом поменять алгоритм получения table name, не через regexp, а тест это будет тестировать, что ты ничего не поломал

2024-02-21 08:13 UTC, fantom0005 requested changes

2024-02-21 08:13 UTC, fantom0005 commented on scope.go
> +	if len(m) == 0 {
что будет, если он найдет 2?
тоже нужно обработать

2024-02-21 08:13 UTC, fantom0005 commented on scope.go
> +	for _, match := range m {
почему тут for? мы же ожидаем, что один create query будет.

2024-02-21 08:13 UTC, fantom0005 commented on scope.go
> +	m := re.FindAllStringSubmatch(query, -1)
однобуквенная переменная

2024-02-22 12:15 UTC, fantom0005 approved these changes

2024-02-22 15:34 UTC, merged